baseURL = 'https://ricovz.me/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
disableHugoGeneratorInject = 'true'
title = 'Rico van Zelst'
theme = ['hugo-cloak-email', 'archie']
enableEmoji = 'true'
enableRobotsTXT = 'true'
timeZone = 'Europe/Amsterdam'
watch = 'true'
enableInlineShortcodes = true
pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN = false
	subtitle = "19-year-old software engineer, willing to assist organizations in building the best technical solutions in today’s competitive market."
	mathjax = false
	katex = false
    favicon = "/rico-logo.png"
	exclude = ["/content/about.md"]
	description = "Rico van Zelst: 19-year-old software engineer, willing to assist organizations in building the best technical solutions in today’s competitive market."

# Socials
[[params.social]]
	name = "Email"
	icon = "mail"
	url = "mailto:ricovzelst@pm.me"

[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/rico-vz"

[[params.social]]
	name = "LinkedIn"
	icon = "linkedin"
	url = "https://www.linkedin.com/in/ricovz/"


# Main menu
[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 2

[[menu.main]]
	name = "Blog"
	url = "/blog"
	weight = 3

[[menu.main]]
	name = "Contact"
	url = "/contact"
	weight = 4